services:
  backend:
    build:
      context: ./extraction
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./extraction:/app
    environment:
      - PYTHONUNBUFFERED=1

  backend2:
    build:
      context: ./prediction
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./prediction:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: bash -c "npm install && npm run serve"
