version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:5000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  backend1:
    build:
      context: ./backend1
    ports:
      - "5001:5001"
    networks:
      - app-network

  backend2:
    build:
      context: ./backend2
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
