services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  backend2:
    build:
      context: ./backend2
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend2:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./fire_detection:/app
    ports:
      - "8080:8080"
    command: bash -c "npm install && npm run serve"
