version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0

  frontend:
    build:
      context: ./fire_detection
    volumes:
      - ./fire_detection:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend
