version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./fire_detection
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
